In [1]:
# import libraries
import pandas as pd
import numpy as np
import sqlite3

In [74]:
# Load dataset
df = pd.read_csv("nykaa_campaign_data.csv")

df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [5]:
# Basic exploration
df.shape

(55555, 16)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
dtypes: float64(3), int64(6), object(7)
memory usage: 6.8+ MB

In [11]:
df.describe().round(2)

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00
mean,17.45,55087.89,4688.07,1877.27,1032.87,515819.72,377.35,2.71,13.78
std,7.52,25930.00,3178.69,1435.64,862.50,490012.11,541.08,4.49,6.35
min,5.00,10001.00,202.00,56.00,19.00,6183.00,9.08,-0.97,2.60
25%,11.00,32680.00,2110.00,779.00,400.00,177706.00,105.44,0.04,8.36
50%,17.00,55182.00,3907.00,1481.00,779.00,360436.00,207.51,1.24,13.60
75%,24.00,77514.50,6688.00,2605.00,1414.00,687422.50,428.58,3.63,18.86
max,30.00,100000.00,14868.00,8876.00,6686.00,4579910.00,15473.16,74.42,30.91

In [13]:
df.columns

Index(['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration',
       'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions',
       'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score',
       'Customer_Segment', 'Date'],
      dtype='object')

In [15]:
# Check missing values
df.isnull().sum()

Campaign_ID         0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Impressions         0
Clicks              0
Leads               0
Conversions         0
Revenue             0
Acquisition_Cost    0
ROI                 0
Language            0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [17]:
(df.isnull().sum()/len(df))*100

Campaign_ID         0.0
Campaign_Type       0.0
Target_Audience     0.0
Duration            0.0
Channel_Used        0.0
Impressions         0.0
Clicks              0.0
Leads               0.0
Conversions         0.0
Revenue             0.0
Acquisition_Cost    0.0
ROI                 0.0
Language            0.0
Engagement_Score    0.0
Customer_Segment    0.0
Date                0.0
dtype: float64

In [19]:
# Check duplicate rows
df.duplicated().sum()

0

In [76]:
# Standardize column names
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

In [23]:
df.columns

Index(['campaign_id', 'campaign_type', 'target_audience', 'duration',
       'channel_used', 'impressions', 'clicks', 'leads', 'conversions',
       'revenue', 'acquisition_cost', 'roi', 'language', 'engagement_score',
       'customer_segment', 'date'],
      dtype='object')

In [84]:
# Convert date column
df["date"] = pd.to_datetime(
    df["date"],
    dayfirst=True
)
# Extract all date parts 
df['Month']        = df['date'].dt.month          # 1-12
df['Month_Name']   = df['date'].dt.strftime('%B') # July, August...
df['Month_Year']   = df['date'].dt.to_period('M').astype(str)  # 2024-07
df['Year']         = df['date'].dt.year           # 2024, 2025
df.head(2)

,campaign_id,campaign_type,target_audience,duration,channel_used,impressions,clicks,leads,conversions,revenue,acquisition_cost,roi,language,engagement_score,customer_segment,date,Month,Month_Name,Month_Year,Year
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,2025-04-29,4,April,2025-04,2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,2025-04-06,4,April,2025-04,2025

In [29]:
df.dtypes

campaign_id                 object
campaign_type               object
target_audience             object
duration                     int64
channel_used                object
impressions                  int64
clicks                       int64
leads                        int64
conversions                  int64
revenue                      int64
acquisition_cost           float64
roi                        float64
language                    object
engagement_score           float64
customer_segment            object
date                datetime64[ns]
dtype: object

In [37]:
# check numerical columns
num_cols=df.select_dtypes(include="number").columns
df[num_cols].describe().round(2)

,duration,impressions,clicks,leads,conversions,revenue,acquisition_cost,roi,engagement_score
count,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00,55555.00
mean,17.45,55087.89,4688.07,1877.27,1032.87,515819.72,377.35,2.71,13.78
std,7.52,25930.00,3178.69,1435.64,862.50,490012.11,541.08,4.49,6.35
min,5.00,10001.00,202.00,56.00,19.00,6183.00,9.08,-0.97,2.60
25%,11.00,32680.00,2110.00,779.00,400.00,177706.00,105.44,0.04,8.36
50%,17.00,55182.00,3907.00,1481.00,779.00,360436.00,207.51,1.24,13.60
75%,24.00,77514.50,6688.00,2605.00,1414.00,687422.50,428.58,3.63,18.86
max,30.00,100000.00,14868.00,8876.00,6686.00,4579910.00,15473.16,74.42,30.91

In [39]:
# check negative values
cols = [
    "duration",
    "impressions",
    "clicks",
    "leads",
    "conversions",
    "revenue",
    "acquisition_cost"
]

for col in cols:
    print(col)
    print((df[col] < 0).sum())

duration
0
impressions
0
clicks
0
leads
0
conversions
0
revenue
0
acquisition_cost
0

In [43]:
# Logical Validation
# Clicks should never exceed Impressions
(df["clicks"] > df["impressions"]).sum()

0

In [45]:
# Leads should never exceed Clicks
(df["leads"] > df["clicks"]).sum()

0

In [47]:
# Conversions should never exceed Leads
(df["conversions"] > df["leads"]).sum()

0

In [49]:
# Checking Outliers
num_cols = [
    "revenue",
    "acquisition_cost",
    "roi",
    "engagement_score"
]

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3-Q1

    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    outliers = df[(df[col]<lower)|(df[col]>upper)]

    print(col, len(outliers))

revenue 3156
acquisition_cost 4845
roi 4081
engagement_score 0

In [53]:
# Check unique updates
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    print(f"{col}: {df[col].nunique()} unique values")

campaign_id: 55555 unique values
campaign_type: 5 unique values
target_audience: 5 unique values
channel_used: 156 unique values
language: 4 unique values
customer_segment: 5 unique values

In [55]:
# create month column
df["month"] = df["date"].dt.month_name()

In [57]:
# Duration Bucket
df["duration_bucket"] = np.where(
    df["duration"]<=10,
    "Short",
    np.where(
        df["duration"]<=20,
        "Medium",
        "Long"
    )
)

In [5]:
df.to_csv(
    "nykaa_campaign_clean.csv",
    index=False
)

In [7]:
conn = sqlite3.connect("nykaa.db")

In [90]:
df.to_sql(
    "campaigns",
    conn,
    if_exists="replace",
    index=False
)

55555

## Which campaign type generates the highest revenue and ROI?

In [22]:
query = """
SELECT
    campaign_type,
    SUM(revenue) AS Total_Revenue,
    ROUND(AVG(roi),2) AS Avg_ROI
FROM campaigns
GROUP BY campaign_type
ORDER BY Total_Revenue DESC;
"""

result = pd.read_sql(query, conn)

result

  Campaign_Type  Total_Revenue  Avg_ROI
0    Influencer     5769064044     2.70
1  Social Media     5751837620     2.75
2      Paid Ads     5751468983     2.72
3           SEO     5698831847     2.71
4         Email     5685161788     2.68

## What percentage of total revenue comes from each audience segment?

In [25]:
query = """
SELECT
    target_audience,
    SUM(revenue) AS Revenue,
    ROUND(
        100.0 * SUM(revenue) /
        (SELECT SUM(revenue) FROM campaigns),
        2
    ) AS Revenue_Share
FROM campaigns
GROUP BY target_audience
ORDER BY Revenue DESC;
"""

result = pd.read_sql(query, conn)

result

         Target_Audience     Revenue  Revenue_Share
0       Premium Shoppers  5852284945          20.42
1       College Students  5786247365          20.19
2          Working Women  5743709729          20.04
3  Tier 2 City Customers  5701063841          19.89
4                  Youth  5573058402          19.45

## Which campaigns have negative ROI and how much revenue are they collectively wasting?

In [28]:
query = """
SELECT
    campaign_type,
    target_audience,
    COUNT(*) AS Campaigns,
    SUM(revenue) AS Revenue,
    SUM(acquisition_cost) AS Cost
FROM campaigns
WHERE roi < 0
GROUP BY
    campaign_type,
    target_audience
ORDER BY Cost DESC;
"""

result = pd.read_sql(query, conn)

result

   Campaign_Type        Target_Audience  Campaigns   Revenue       Cost
0     Influencer          Working Women        593  69892202  579124.03
1          Email                  Youth        564  64654693  572001.99
2       Paid Ads                  Youth        562  66843248  563488.79
3          Email  Tier 2 City Customers        544  63622807  544516.66
4            SEO                  Youth        536  63486362  538515.54
5   Social Media  Tier 2 City Customers        536  61781473  528267.40
6          Email       College Students        563  65796568  528055.61
7            SEO       Premium Shoppers        528  63417399  527382.55
8   Social Media       Premium Shoppers        539  62654567  527105.63
9            SEO  Tier 2 City Customers        516  60422583  522014.58
10      Paid Ads  Tier 2 City Customers        541  64466131  521666.59
11    Influencer       College Students        545  65897313  521584.07
12      Paid Ads          Working Women        546  66147820  521033.92
13  Social Media          Working Women        515  58221363  516606.03
14      Paid Ads       Premium Shoppers        520  59843510  516059.05
15           SEO          Working Women        525  61404318  514990.88
16         Email       Premium Shoppers        491  56374874  505145.63
17    Influencer  Tier 2 City Customers        535  66342355  502292.61
18           SEO       College Students        525  61486652  500796.95
19      Paid Ads       College Students        499  60312728  495073.07
20    Influencer                  Youth        491  58295753  490557.44
21         Email          Working Women        524  62812455  486557.57
22    Influencer       Premium Shoppers        489  57699426  485991.14
23  Social Media       College Students        500  60099384  484451.52
24  Social Media                  Youth        493  56811621  482853.87

## For each campaign type, what is the revenue earned per rupee spent on acquisition?

In [31]:
query = """
SELECT
    campaign_type,
    ROUND(
        SUM(revenue) /
        SUM(acquisition_cost),
        2
    ) AS Revenue_Per_Rupee
FROM campaigns
GROUP BY campaign_type
ORDER BY Revenue_Per_Rupee DESC;
"""

result = pd.read_sql(query, conn)

result

  Campaign_Type  Revenue_Per_Rupee
0  Social Media            1386.50
1    Influencer            1379.94
2      Paid Ads            1364.73
3           SEO            1358.14
4         Email            1345.92

## What does the full conversion funnel look like for each audience segment?

In [34]:
query = """
SELECT

    target_audience,

    SUM(impressions) AS Impressions,

    SUM(clicks) AS Clicks,

    SUM(leads) AS Leads,

    SUM(conversions) AS Conversions,

    ROUND(
        100.0 * SUM(clicks) /
        SUM(impressions),
        2
    ) AS CTR,

    ROUND(
        100.0 * SUM(leads) /
        SUM(clicks),
        2
    ) AS Lead_Rate,

    ROUND(
        100.0 * SUM(conversions) /
        SUM(leads),
        2
    ) AS Conversion_Rate

FROM campaigns

GROUP BY target_audience;
"""

result = pd.read_sql(query, conn)

result

,Target_Audience,Impressions,Clicks,Leads,Conversions,CTR,Lead_Rate,Conversion_Rate
0,College Students,613106385,52493532,21024185,11579074,8.56,40.05,55.08
1,Premium Shoppers,619879502,52899834,21254764,11703289,8.53,40.18,55.06
2,Tier 2 City Customers,610159827,51899333,20787495,11419296,8.51,40.05,54.93
3,Working Women,615684565,52498699,20866491,11494222,8.53,39.75,55.08
4,Youth,601577192,50654359,20358862,11185041,8.42,40.19,54.94

## Which audience segment has the highest drop-off between leads and final conversion?

In [37]:
query = """
SELECT

    target_audience,

    ROUND(
        100.0 * SUM(conversions) /
        SUM(leads),
        2
    ) AS Lead_To_Conversion_Rate

FROM campaigns

GROUP BY target_audience

ORDER BY Lead_To_Conversion_Rate;
"""

result = pd.read_sql(query, conn)

result

         Target_Audience  Lead_To_Conversion_Rate
0  Tier 2 City Customers                    54.93
1                  Youth                    54.94
2       Premium Shoppers                    55.06
3       College Students                    55.08
4          Working Women                    55.08

## Which campaign type drives the most clicks but fails to convert to revenue?

In [40]:
query = """
SELECT

    campaign_type,

    SUM(clicks) AS Clicks,

    SUM(conversions) AS Conversions,

    SUM(revenue) AS Revenue

FROM campaigns

GROUP BY campaign_type

ORDER BY Clicks DESC;
"""

result = pd.read_sql(query, conn)

result

  Campaign_Type    Clicks  Conversions     Revenue
0  Social Media  52521898     11595675  5751837620
1    Influencer  52444314     11563919  5769064044
2      Paid Ads  52199354     11425573  5751468983
3         Email  51664577     11425766  5685161788
4           SEO  51615614     11369989  5698831847

## What is the optimal campaign duration to maximize ROI?

In [45]:
query = """
SELECT

CASE

WHEN duration <= 10 THEN 'Short'

WHEN duration <= 20 THEN 'Medium'

ELSE 'Long'

END AS Duration_Bucket,

ROUND(
    AVG(roi),
    2
) AS Avg_ROI

FROM campaigns

GROUP BY Duration_Bucket
Order by Avg_ROI;
"""

result = pd.read_sql(query, conn)

result

  Duration_Bucket  Avg_ROI
0           Short     2.67
1            Long     2.70
2          Medium     2.76

## How has monthly revenue and conversion performance trended over time?

In [92]:
query = """
SELECT
    Month_Year,
    SUM(revenue) AS Total_Revenue,
    ROUND(AVG(roi), 2) AS Avg_ROI
FROM campaigns
GROUP BY Month_Year
ORDER BY Month_Year;
"""

monthly_trend = pd.read_sql(query, conn)
monthly_trend

   Month_Year  Total_Revenue  Avg_ROI
0     2024-07     2630226313     2.81
1     2024-08     2597876736     2.77
2     2024-09     2390680030     2.67
3     2024-10     2583203421     2.62
4     2024-11     2523763004     2.75
5     2024-12     2586353806     2.71
6     2025-01     2521812438     2.65
7     2025-02     2333105678     2.76
8     2025-03     2570717938     2.73
9     2025-04     2439364737     2.64
10    2025-05     2572782370     2.78
11    2025-06      906477811     2.60


## During which months does ROI drop the most, and what campaign types are running then?

In [97]:
query = """
WITH monthly_roi AS (
    SELECT
        Month_Year,
        ROUND(AVG(ROI), 2) AS Avg_ROI
    FROM campaigns
    GROUP BY Month_Year
),

roi_change AS (
    SELECT
        Month_Year,
        Avg_ROI,
        LAG(Avg_ROI) OVER (ORDER BY Month_Year) AS Previous_Month_ROI,
        ROUND(
            Avg_ROI - LAG(Avg_ROI) OVER (ORDER BY Month_Year),
            2
        ) AS ROI_Change
    FROM monthly_roi
),

campaign_breakdown AS (
    SELECT
        Month_Year,
        Campaign_Type,
        COUNT(*) AS Campaign_Count,
        ROUND(AVG(ROI), 2) AS Campaign_Avg_ROI
    FROM campaigns
    GROUP BY Month_Year, Campaign_Type
)

SELECT
    r.Month_Year,
    r.Avg_ROI,
    r.Previous_Month_ROI,
    r.ROI_Change,
    c.Campaign_Type,
    c.Campaign_Count,
    c.Campaign_Avg_ROI
FROM roi_change r
JOIN campaign_breakdown c
    ON r.Month_Year = c.Month_Year
WHERE r.ROI_Change < 0
ORDER BY r.ROI_Change ASC, c.Campaign_Avg_ROI ASC;
"""

result = pd.read_sql(query, conn)
result

,Month_Year,Avg_ROI,Previous_Month_ROI,ROI_Change,Campaign_Type,Campaign_Count,Campaign_Avg_ROI
0,2025-06,2.60,2.78,-0.18,SEO,410,2.37
1,2025-06,2.60,2.78,-0.18,Social Media,350,2.43
2,2025-06,2.60,2.78,-0.18,Email,362,2.54
3,2025-06,2.60,2.78,-0.18,Influencer,352,2.82
4,2025-06,2.60,2.78,-0.18,Paid Ads,360,2.86
5,2024-09,2.67,2.77,-0.10,Influencer,934,2.51
6,2024-09,2.67,2.77,-0.10,Email,884,2.65
7,2024-09,2.67,2.77,-0.10,Social Media,912,2.66
8,2024-09,2.67,2.77,-0.10,Paid Ads,969,2.71
9,2024-09,2.67,2.77,-0.10,SEO,972,2.83
10,2025-04,2.64,2.73,-0.09,Email,949,2.50
11,2025-04,2.64,2.73,-0.09,Social Media,976,2.61
12,2025-04,2.64,2.73,-0.09,SEO,975,2.63
13,2025-04,2.64,2.73,-0.09,Influencer,1017,2.69
14,2025-04,2.64,2.73,-0.09,Paid Ads,930,2.80
15,2025-01,2.65,2.71,-0.06,Paid Ads,1003,2.54
16,2025-01,2.65,2.71,-0.06,Email,997,2.63
17,2025-01,2.65,2.71,-0.06,Influencer,955,2.66
18,2025-01,2.65,2.71,-0.06,SEO,988,2.71
19,2025-01,2.65,2.71,-0.06,Social Media,974,2.74
20,2024-10,2.62,2.67,-0.05,Influencer,1004,2.51
21,2024-10,2.62,2.67,-0.05,Social Media,1025,2.53
22,2024-10,2.62,2.67,-0.05,Paid Ads,1024,2.60
23,2024-10,2.62,2.67,-0.05,Email,1033,2.72
24,2024-10,2.62,2.67,-0.05,SEO,982,2.74
25,2024-12,2.71,2.75,-0.04,Influencer,992,2.54
26,2024-12,2.71,2.75,-0.04,SEO,971,2.63
27,2024-08,2.77,2.81,-0.04,Social Media,990,2.66
28,2024-12,2.71,2.75,-0.04,Paid Ads,976,2.69
29,2024-12,2.71,2.75,-0.04,Email,1023,2.73
30,2024-08,2.77,2.81,-0.04,Email,971,2.75
31,2024-08,2.77,2.81,-0.04,Influencer,987,2.77
32,2024-08,2.77,2.81,-0.04,SEO,1004,2.79
33,2024-08,2.77,2.81,-0.04,Paid Ads,991,2.88
34,2024-12,2.71,2.75,-0.04,Social Media,1002,2.95
35,2025-03,2.73,2.76,-0.03,Paid Ads,1001,2.68
36,2025-03,2.73,2.76,-0.03,Email,979,2.69
37,2025-03,2.73,2.76,-0.03,Influencer,968,2.69
38,2025-03,2.73,2.76,-0.03,SEO,1023,2.71
39,2025-03,2.73,2.76,-0.03,Social Media,981,2.91

## Do Hindi campaigns outperform English campaigns for Tier 2 City customers?

In [100]:
query = """
SELECT

language,

SUM(revenue) AS Revenue,

ROUND(
AVG(roi),
2
) AS Avg_ROI,

ROUND(
AVG(engagement_score),
2
) AS Avg_Engagement

FROM campaigns

WHERE target_audience = 'Tier 2 City Customers'

GROUP BY language;
"""

result = pd.read_sql(query, conn)

result

  language     Revenue  Avg_ROI  Avg_Engagement
0  Bengali  1448857284     2.76           13.78
1  English  1351831205     2.61           13.62
2    Hindi  1440783024     2.65           13.75
3    Tamil  1459592328     2.70           13.88

## Which language has the highest engagement score and does it also convert better?

In [103]:
query = """
SELECT

language,

ROUND(
AVG(engagement_score),
2
) AS Engagement,

ROUND(
100.0 * SUM(conversions) /
SUM(leads),
2
) AS Conversion_Rate

FROM campaigns

GROUP BY language;
"""

result = pd.read_sql(query, conn)

result

  language  Engagement  Conversion_Rate
0  Bengali       13.80            54.87
1  English       13.77            54.76
2    Hindi       13.79            55.33
3    Tamil       13.78            55.12

## Which combination of campaign type, audience, and language gives the highest ROI?

In [106]:
query = """
SELECT *

FROM (

SELECT

campaign_type,

target_audience,

language,

ROUND(
AVG(roi),
2
) AS Avg_ROI,

RANK() OVER(

ORDER BY AVG(roi) DESC

) AS Ranking

FROM campaigns

GROUP BY

campaign_type,

target_audience,

language

)

WHERE Ranking <= 10;
"""

result = pd.read_sql(query, conn)

result

  campaign_type   target_audience language  Avg_ROI  Ranking
0    Influencer  Premium Shoppers    Hindi     3.16        1
1         Email     Working Women    Tamil     3.08        2
2      Paid Ads             Youth    Hindi     3.05        3
3  Social Media  College Students    Hindi     3.04        4
4    Influencer  College Students  Bengali     3.02        5
5           SEO  College Students  English     3.02        6
6  Social Media  College Students    Tamil     3.02        7
7  Social Media             Youth  English     3.00        8
8      Paid Ads  College Students  English     2.99        9
9           SEO     Working Women    Hindi     2.98       10

## Within each campaign type, which audience segment delivers the best conversion rate?

In [109]:
query = """
WITH rates AS (

SELECT

campaign_type,

target_audience,

ROUND(
100.0 * SUM(conversions) /
SUM(leads),
2
) AS Conversion_Rate

FROM campaigns

GROUP BY

campaign_type,

target_audience

)

SELECT *

FROM (

SELECT *,

RANK() OVER(

PARTITION BY campaign_type

ORDER BY Conversion_Rate DESC

) AS Rank_No

FROM rates

)

WHERE Rank_No = 1;
"""

result = pd.read_sql(query, conn)

result

  campaign_type        target_audience  Conversion_Rate  Rank_No
0         Email       Premium Shoppers            55.66        1
1    Influencer  Tier 2 City Customers            55.41        1
2    Influencer          Working Women            55.41        1
3      Paid Ads       College Students            55.87        1
4           SEO                  Youth            55.21        1
5  Social Media       College Students            55.19        1
6  Social Media          Working Women            55.19        1

## Campaigns Performing Above Average ROI

In [131]:
query = """
WITH avg_roi AS (
    SELECT
        campaign_type,
        AVG(roi) AS Avg_ROI
    FROM campaigns
    GROUP BY campaign_type
),

ranked_campaigns AS (
    SELECT
        c.campaign_id,
        c.campaign_type,
        c.roi,
        a.Avg_ROI,

        ROW_NUMBER() OVER (
            PARTITION BY c.campaign_type
            ORDER BY c.roi DESC
        ) AS rn

    FROM campaigns c

    JOIN avg_roi a
        ON c.campaign_type = a.campaign_type

    WHERE c.roi > a.Avg_ROI
)

SELECT
    campaign_id,
    campaign_type,
    roi,
    ROUND(Avg_ROI, 2) AS Avg_ROI
FROM ranked_campaigns
WHERE rn <= 5
ORDER BY campaign_type, roi DESC;
"""

result = pd.read_sql(query, conn)

result

     campaign_id campaign_type    roi  Avg_ROI
0    NY-CMP-5736         Email  53.70     2.68
1   NY-CMP-13538         Email  49.58     2.68
2   NY-CMP-22849         Email  42.95     2.68
3   NY-CMP-53612         Email  40.73     2.68
4   NY-CMP-31568         Email  40.35     2.68
5   NY-CMP-22689    Influencer  66.32     2.70
6    NY-CMP-2174    Influencer  55.27     2.70
7   NY-CMP-35197    Influencer  52.53     2.70
8   NY-CMP-33859    Influencer  47.65     2.70
9   NY-CMP-44366    Influencer  46.29     2.70
10  NY-CMP-13007      Paid Ads  74.42     2.72
11  NY-CMP-49715      Paid Ads  65.00     2.72
12  NY-CMP-26356      Paid Ads  64.14     2.72
13  NY-CMP-39329      Paid Ads  59.64     2.72
14  NY-CMP-44966      Paid Ads  49.98     2.72
15  NY-CMP-32975           SEO  49.56     2.71
16   NY-CMP-3383           SEO  46.58     2.71
17  NY-CMP-55921           SEO  46.41     2.71
18   NY-CMP-1227           SEO  45.77     2.71
19  NY-CMP-33011           SEO  45.76     2.71
20  NY-CMP-51204  Social Media  54.74     2.75
21  NY-CMP-24042  Social Media  52.45     2.75
22  NY-CMP-52214  Social Media  50.44     2.75
23  NY-CMP-39427  Social Media  46.52     2.75
24  NY-CMP-47645  Social Media  46.47     2.75

## Cumulative Revenue

In [127]:
query = """
WITH monthly AS (
    SELECT
        Month_Year,
        SUM(Revenue) AS Revenue
    FROM campaigns
    GROUP BY Month_Year
)

SELECT
    Month_Year,
    Revenue,
    SUM(Revenue) OVER (
        ORDER BY Month_Year
    ) AS Cumulative_Revenue
FROM monthly
ORDER BY Month_Year;
"""
result = pd.read_sql(query, conn)

result

   Month_Year     Revenue  Cumulative_Revenue
0     2024-07  2630226313          2630226313
1     2024-08  2597876736          5228103049
2     2024-09  2390680030          7618783079
3     2024-10  2583203421         10201986500
4     2024-11  2523763004         12725749504
5     2024-12  2586353806         15312103310
6     2025-01  2521812438         17833915748
7     2025-02  2333105678         20167021426
8     2025-03  2570717938         22737739364
9     2025-04  2439364737         25177104101
10    2025-05  2572782370         27749886471
11    2025-06   906477811         28656364282